routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);
Route::get('home', ['as' => 'home', 'uses' => 'DashboardController@index']);

Route::group(['prefix' => 'categories', 'as' => 'category.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'CategoryController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'CategoryController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'CategoryController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'CategoryController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CategoryController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'CategoryController@update']);
});

Route::group(['prefix' => 'tables', 'as' => 'table.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'TableController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'TableController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'TableController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'TableController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'TableController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'TableController@update']);
});

Route::group(['prefix' => 'pos', 'as' => 'pos.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'PosController@index']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'PosController@edit']);
    Route::post('/', ['as' => 'add', 'uses' => 'PosController@add']);
    Route::get('orderList', 'PosController@orderList');
    Route::get('orderList/{id}', 'PosController@orderListEdit');
    Route::get('total', 'PosController@total');
    Route::get('total/{id}', 'PosController@totalEdit');
    Route::post('update', 'PosController@update');
    Route::put('process', ['as' => 'process', 'uses' => 'PosController@process']);
    Route::get('delete/{id}', ['as' => 'delete', 'uses' => 'PosController@destroy']);
    Route::post('payment', ['as' => 'payment', 'uses' => 'PosController@payment']);
    Route::get('payment/{id}', ['as' => 'paymentDetail', 'uses' => 'PosController@paymentDetail']);
});

Route::group(['prefix' => 'products', 'as' => 'product.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'ProductController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'ProductController@store']);
    Route::get('inventory', ['as' => 'inventory', 'uses' => 'ProductController@inventory']);
    Route::get('new', ['as' => 'create', 'uses' => 'ProductController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ProductController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'ProductController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'ProductController@update']);

});

Route::group(['prefix' => 'sales', 'as' => 'sale.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'SaleController@index']);
    Route::get('opened', ['as' => 'opened', 'uses' => 'SaleController@opened']);
    Route::get('show/{id}', ['as' => 'show', 'uses' => 'SaleController@show']);
    Route::post('payment', ['as' => 'payment', 'uses' => 'SaleController@payment']);
    Route::get('payment/{id}', ['as' => 'paymentDetail', 'uses' => 'SaleController@paymentDetail']);
});

Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'UserController@index']);
    Route::get('activity', ['as' => 'activity', 'uses' => 'UserController@activity']);
    Route::post('/', ['as' => 'store', 'uses' => 'UserController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'UserController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'UserController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'UserController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'UserController@update']);
});

Route::group(['prefix' => 'settings', 'as' => 'setting.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'SettingController@index']);
    Route::put('/', ['as' => 'update', 'uses' => 'SettingController@update']);
});

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@loginForm']);
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function orders()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Spatie\Activitylog\Models\Activity;

class UserController extends Controller
{

    public function index()
    {

        $users = User::paginate(20);
        return view('users.index', \compact('users'));
    }

    public function activity()
    {

        $activities = Activity::orderBy('created_at', 'DESC')->paginate(100);
        return view('users.activity', \compact('activities'));
    }

    public function create()
    {
        $roles = Role::all();
        return view('users.create', \compact('roles'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'     => 'required',
            'email'    => 'required|unique:users,email',
            'password' => 'required|string|min:6',
            'role'     => 'required',
        ]);
        if ($validator->fails()) {
            flash('Warning: Please check the form carefully for errors!')->error();
            return back()->withInput()->withErrors($validator);
        }
        $user                    = new User();
        $user->name              = $request->name;
        $user->email             = $request->email;
        $user->email_verified_at = Carbon::now();
        $user->password          = bcrypt($request->password);
        $user->save();
        $user->attachRole($request->role);

        flash('Success: You have saved user!')->success();
        return back();
    }

    public function edit($id)
    {
        $roles = Role::all();
        $user  = User::find($id);
        return view('users.edit', \compact('user', 'roles'));
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name'     => 'required',
            'password' => 'nullable|string|min:6',
            'role'     => 'required',
        ]);
        if ($validator->fails()) {
            flash('Warning: Please check the form carefully for errors!')->error();
            return back()->withInput()->withErrors($validator);
        }
        $user       = User::find($id);
        $user->name = $request->name;
        if (!empty($request->password)) {
            $user->password = bcrypt($request->password);
        }
        $user->save();
        $user->syncRoles([$request->role]);

        flash('Success: You have modified user!')->success();
        return back();
    }

    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        flash('Success: User deleted successfully.')->success();
        return back();
    }
}

resources/views/users/activity.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="animated fadeIn">
        @include('flash::message')
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-5">
                        <h4 class="card-title mb-0">User activity</h4>
                    </div>
                </div>
                <table class="table table-responsive-sm table-hover mt-4 table-sm">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Description</th>
                            <th>User</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($activities as $item)
                        <tr>
                            <td>{{$item->created_at->format('d/m/Y')}}</td>
                            <td>{{$item->description}}</td>
                            <td>{{$item->causer->name}}</td>
                        </tr>
                        @empty
                        <tr>
                            <td class="table-empty" colspan="3">
                                <div class="table-empty-msg">
                                    <i class="fa fa-warning table-empty-icon"></i> No
                                    records
                                    found
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>

                @if ($activities->hasPages())
                {!! $activities->appends(\Request::except('page'))->render() !!}
                @endif
            </div>
        </div>
    </div>
</div>
@stop

resources/views/users/create.blade.php
@extends('layouts.master')

@section('content')
<form action="{{route('user.store')}}" class="form-horizontal" method="POST">
    @csrf
    <div class="container">
        @include('flash::message')
        <div class="row">
            <div class="col-md-8">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-4">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">User Detail</strong>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="inputName">Full Name</label>
                                <input class="form-control{{$errors->has('name')?' is-invalid':''}}" name="name" id="inputName"
                                    type="text" placeholder="e.g. Heru Prasetyo" value="{{old('name')}}">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="inputEmail">Email</label>
                                <input class="form-control{{$errors->has('email')?' is-invalid':''}}" name="email" id="inputEmail"
                                    type="text" placeholder="e.g. example@mail.com" value="{{old('email')}}">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="inputPassword">Password</label>
                                <div class="input-group">
                                    <input type="password" id="input-password" name="password" class="form-control{{$errors->has('password')?' is-invalid':''}}">
                                    <span class="input-group-append">
                                        <button type="button" class="btn btn-default" data-toggle="password-generate">Generate
                                            Password</button>
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" data-toggle="pass-show"> Tampilkan Password
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Accessibility</strong>
                                </div>
                            </div>
                            <div class="form-group mt-2">
                                @foreach ($roles as $role)
                                <div class="form-check">
                                    <input name="role" class="form-check-input" id="radio-{{$role->name}}" type="radio"
                                        value="{{$role->name}}" name="active"
                                        {{old('role',$roles->first()->name)==$role->name?"checked":""}}>
                                    <label class="form-check-label" for="radio-{{$role->name}}">{{$role->display_name}}</label>
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <hr>
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="form-actions float-right">`
                    <button class="btn btn-secondary" type="button">Cancel</button>
                    <button class="btn btn-primary" type="submit">Save User</button>
                </div>
            </div>
        </div>
    </div>
</form>
@stop

resources/views/users/edit.blade.php
@extends('layouts.master')

@section('content')
<form action="{{route('user.update',$user->id)}}" class="form-horizontal" method="POST">
    @csrf
    <input name="_method" type="hidden" value="PUT">
    <div class="container">
        @include('flash::message')
        <div class="row">
            <div class="col-md-8">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-4">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">User Detail</strong>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="inputName">Full Name</label>
                                <input class="form-control{{$errors->has('name')?' is-invalid':''}}" name="name" id="inputName"
                                    type="text" placeholder="e.g. Heru Prasetyo" value="{{old('name',$user->name)}}">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="inputEmail">Email</label>
                                <input class="form-control{{$errors->has('email')?' is-invalid':''}}" name="email" id="inputEmail"
                                    type="text" placeholder="e.g. example@mail.com" value="{{old('email',$user->email)}}"
                                    readonly>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="inputPassword">Password</label>
                                <div class="input-group">
                                    <input type="password" id="input-password" name="password" class="form-control{{$errors->has('password')?' is-invalid':''}}">
                                    <span class="input-group-append">
                                        <button type="button" class="btn btn-default" data-toggle="password-generate">Generate
                                            Password</button>
                                    </span>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" data-toggle="pass-show"> Tampilkan Password
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Accessibility</strong>
                                </div>
                            </div>
                            <div class="form-group mt-2">
                                @foreach ($roles as $role)
                                <div class="form-check">
                                    <input name="role" class="form-check-input" id="radio-{{$role->name}}" type="radio"
                                        value="{{$role->name}}" name="active"
                                        {{old('role',$user->roles()->first()->name)==$role->name?"checked":""}}>
                                    <label class="form-check-label" for="radio-{{$role->name}}">{{$role->display_name}}</label>
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <hr>
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="form-actions float-right">`
                    <button class="btn btn-secondary" type="button">Cancel</button>
                    <button class="btn btn-primary" type="submit">Save User</button>
                </div>
            </div>
        </div>
    </div>
</form>
@stop

resources/views/users/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="animated fadeIn">
        @include('flash::message')
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-5">
                        <h4 class="card-title mb-0">Manage user</h4>
                    </div>
                    <div class="col-sm-7 d-none d-md-block">
                        <a class="btn btn-primary float-right" href="{{route('user.create')}}">
                            Add user
                        </a>
                    </div>
                </div>
                <table class="table table-responsive-sm table-hover mt-4">
                    <thead>
                        <tr>
                            <th class="text-center" width="10">
                                <input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" />
                            </th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($users as $user)
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="selected[]" value="{{$user->id}}" />
                            </td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->roles()->first()->display_name}}</td>
                            <td class="text-right">
                                <div class="dropdown">
                                    <button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{{route('user.edit',$user->id)}}">Edit</a>
                                        @if ($user->id != auth()->user()->id)
                                        <a class="dropdown-item" href="{{route('user.destroy',$user->id)}}" data-toggle="confirm"
                                            data-message="Are you sure?">Hapus</a>
                                        @endif
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td class="table-empty" colspan="4">
                                <div class="table-empty-msg">
                                    <i class="fa fa-warning table-empty-icon"></i> No
                                    records
                                    found
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>

                @if ($users->hasPages())
                {!! $users->appends(\Request::except('page'))->render() !!}
                @endif
            </div>
        </div>
    </div>
</div>
@stop