routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);
Route::get('home', ['as' => 'home', 'uses' => 'DashboardController@index']);

Route::group(['prefix' => 'categories', 'as' => 'category.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'CategoryController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'CategoryController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'CategoryController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'CategoryController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CategoryController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'CategoryController@update']);
});

Route::group(['prefix' => 'tables', 'as' => 'table.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'TableController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'TableController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'TableController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'TableController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'TableController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'TableController@update']);
});

Route::group(['prefix' => 'pos', 'as' => 'pos.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'PosController@index']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'PosController@edit']);
    Route::post('/', ['as' => 'add', 'uses' => 'PosController@add']);
    Route::get('orderList', 'PosController@orderList');
    Route::get('orderList/{id}', 'PosController@orderListEdit');
    Route::get('total', 'PosController@total');
    Route::get('total/{id}', 'PosController@totalEdit');
    Route::post('update', 'PosController@update');
    Route::put('process', ['as' => 'process', 'uses' => 'PosController@process']);
    Route::get('delete/{id}', ['as' => 'delete', 'uses' => 'PosController@destroy']);
    Route::post('payment', ['as' => 'payment', 'uses' => 'PosController@payment']);
    Route::get('payment/{id}', ['as' => 'paymentDetail', 'uses' => 'PosController@paymentDetail']);
});

Route::group(['prefix' => 'products', 'as' => 'product.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'ProductController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'ProductController@store']);
    Route::get('inventory', ['as' => 'inventory', 'uses' => 'ProductController@inventory']);
    Route::get('new', ['as' => 'create', 'uses' => 'ProductController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ProductController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'ProductController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'ProductController@update']);

});

Route::group(['prefix' => 'sales', 'as' => 'sale.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'SaleController@index']);
    Route::get('opened', ['as' => 'opened', 'uses' => 'SaleController@opened']);
    Route::get('show/{id}', ['as' => 'show', 'uses' => 'SaleController@show']);
    Route::post('payment', ['as' => 'payment', 'uses' => 'SaleController@payment']);
    Route::get('payment/{id}', ['as' => 'paymentDetail', 'uses' => 'SaleController@paymentDetail']);
});

Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'UserController@index']);
    Route::get('activity', ['as' => 'activity', 'uses' => 'UserController@activity']);
    Route::post('/', ['as' => 'store', 'uses' => 'UserController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'UserController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'UserController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'UserController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'UserController@update']);
});

Route::group(['prefix' => 'settings', 'as' => 'setting.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'SettingController@index']);
    Route::put('/', ['as' => 'update', 'uses' => 'SettingController@update']);
});

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@loginForm']);
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
});

app/Models/Product.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes, Sluggable;

    protected $dates = ['deleted_at'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class)->withTrashed();
    }

    public function getCoverAttribute()
    {
        return ($this->image) ? $this->image : "images/no-image.png";
    }

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name',
            ],
        ];
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Api\ApiController;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends ApiController
{
    public function data(Request $request)
    {
        $products = [];
        $results  = Product::orderBy('created_at', 'DESC')->paginate(18);

        foreach ($results as $product) {
            $row              = [];
            $row['id']        = $product->id;
            $row['name']      = $product->name;
            $row['price_old'] = $product->price;
            $row['cover']     = $product->cover;
            $products[]       = $row;
        }
        $data = [
            'current_page'   => $results->currentPage(),
            'products'       => $products,
            'first_page_url' => $results->url(1),
            'from'           => $results->firstItem(),
            'last_page'      => $results->lastPage(),
            'last_page_url'  => $results->url($results->lastPage()),
            'next_page_url'  => $results->nextPageUrl(),
            'per_page'       => $results->perPage(),
            'prev_page_url'  => $results->previousPageUrl(),
            'to'             => $results->count(),
            'total'          => $results->total(),
            'has_more_page'  => $results->hasMorePages(),
        ];
        return $this->sendResponse($data, 'Posts retrieved successfully.');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;
use Image;

class ProductController extends Controller
{

    public function index()
    {
        $products = Product::paginate(20);
        return view('product.index', compact('products'));
    }

    public function inventory()
    {
        return view('product.inventory');
    }

    public function create()
    {
        $categories = Category::all();
        return view('product.create', \compact('categories'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'price' => 'required',
            'image' => 'nullable|mimes:jpeg,jpg,png',
        ]);
        if ($validator->fails()) {
            flash('Warning: Please check the form carefully for errors!')->error();
            return back()->withInput()->withErrors($validator);
        }

        $user     = Auth::user();
        $category = Category::find($request->category);

        $product         = new Product;
        $product->name   = $request->title;
        $product->price  = $request->price;
        $product->status = 1;
        if ($request->hasFile('image')) {
            $image     = $request->file('image');
            $extension = $image->clientExtension();
            $fileName  = str_slug($request->title) . time() . ".{$extension}";
            $path      = public_path('images/products/' . $fileName);
            Image::make($image->getRealPath())->crop(200, 200)->save($path);

            $product->image = "images/products/{$fileName}";
        }

        $product->category()->associate($category);
        $product->user()->associate($user);
        $product->save();

        $user = Auth::user();
        activity()->causedBy($user)->log($user->name . ' menambahkan produk baru.');

        flash('Success: Product has been saved!')->success();
        return redirect()->route('product.index');

    }
    public function edit($id)
    {
        $categories = Category::all();
        $product    = Product::find($id);
        return view('product.edit', compact('product', 'categories'));
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'price' => 'required',
            'image' => 'nullable|mimes:jpeg,jpg,png',
        ]);
        if ($validator->fails()) {
            flash('Warning: Please check the form carefully for errors!')->error();
            return back()->withInput()->withErrors($validator);
        }

        $category = Category::find($request->category);

        $product         = Product::find($id);
        $product->name   = $request->title;
        $product->price  = $request->price;
        $product->status = 1;

        if ($request->hasFile('image')) {
            if (file_exists(public_path($product->image)) && $product->image) {
                File::delete($product->image);
            }

            $image     = $request->file('image');
            $extension = $image->clientExtension();
            $fileName  = str_slug($request->title) . time() . ".{$extension}";
            $path      = public_path('images/products/' . $fileName);
            Image::make($image->getRealPath())->crop(200, 200)->save($path);

            $product->image = "images/products/{$fileName}";
        }

        $product->category()->associate($category);
        $product->save();

        flash('Success:Y ou have modified product!')->success();
        return redirect()->route('product.edit', $id);
    }

    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();

        flash('Success: You have deleted product!')->success();
        return back();
    }

}

resources/views/product/create.blade.php
@extends('layouts.master')

@section('content')
<form class="form-horizontal" action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="container">
        @include('flash::message')
        <div class="row">
            <div class="col-md-8">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">

                            <div class="form-group">
                                <label class="col-form-label" for="inputTitle">Title</label>
                                <input name="title" class="form-control{{$errors->has('title')?' is-invalid':''}}"
                                    value="{{old('title')}}" id="inputTitle" type="text">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="editor">Image</label>
                                <input type="file" name="image">
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Pricing</strong>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputCost">Cost per item</label>
                                <input name="price" id="inputCost" type="number" class="medium" value="{{old('price',0)}}"
                                    data-prefix="Rp." {!!$errors->has('price')?'class="is-invalid"':''!!}>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="animated fadeIn">
                    <div class="card bg-light">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Category</strong>
                                </div>
                            </div>
                            <div class="form-group mt-2">
                                @foreach ($categories as $item)
                                <div class="form-check">
                                    <input class="form-check-input" id="radio-{{$item->id}}" type="radio" value="{{$item->id}}"
                                        name="category" {{old('category',1)?"checked":""}}>
                                    <label class="form-check-label" for="radio-{{$item->id}}">{{$item->name}}</label>
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <hr>
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="form-actions float-right">
                    <button class="btn btn-secondary" type="button">Cancel</button>
                    <button class="btn btn-primary" type="submit">Save Product</button>
                </div>
            </div>
        </div>
    </div>
</form>
@stop
@push('scripts')

@endpush

resources/views/product/edit.blade.php
@extends('layouts.master')

@section('content')
<form class="form-horizontal" action="{{route('product.update',$product->id)}}" method="POST" enctype="multipart/form-data">
    @csrf
    <input name="_method" type="hidden" value="PUT">
    <div class="container">
        @include('flash::message')
        <div class="row">
            <div class="col-md-8">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">

                            <div class="form-group">
                                <label class="col-form-label" for="inputTitle">Title</label>
                                <input name="title" class="form-control{{$errors->has('title')?' is-invalid':''}}"
                                    value="{{old('title',$product->name)}}" id="inputTitle" type="text">
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="editor">Image</label>
                                <input type="file" name="image">
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Pricing</strong>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputCost">Cost per item</label>
                                <input name="price" id="inputCost" type="number" class="medium" data-prefix="Rp." value="{{old('price',$product->price)}}"
                                    {!!$errors->has('price')?'class="is-invalid"':''!!}>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="animated fadeIn">
                    <div class="card bg-light">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Category</strong>
                                </div>
                            </div>
                            <div class="form-group mt-2">
                                @foreach ($categories as $item)
                                <div class="form-check">
                                    <input class="form-check-input" id="radio-{{$item->id}}" type="radio" value="{{$item->id}}"
                                        name="category" {{$item->id == $product->category_id?"checked":""}}>
                                    <label class="form-check-label" for="radio-{{$item->id}}">{{$item->name}}</label>
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <hr>
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="form-actions float-right">
                    <button class="btn btn-secondary" type="button">Cancel</button>
                    <button class="btn btn-primary" type="submit">Save Product</button>
                </div>
            </div>
        </div>
    </div>
</form>
@stop
@push('scripts')
@endpush

resources/views/product/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-5">
                        <h4 class="card-title mb-0">Products</h4>
                        <div class="small text-muted">November 2017</div>
                    </div>
                    <div class="col-sm-7 d-none d-md-block">
                        <a class="btn btn-primary float-right" href="{{route('product.create')}}">
                            Add Product
                        </a>
                    </div>
                </div>
                <table class="table table-responsive-sm table-hover mt-4">
                    <thead>
                        <tr>
                            <th class="text-center">
                                <input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" />
                            </th>
                            <th></th>
                            <th>Product</th>
                            <th>Category</th>
                            <th>Price</th>
                            <th class="text-center">Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($products as $product)
                        <tr>
                            <td class="text-center" width="10">
                                <input type="checkbox" name="selected[]" value="{{$product->id}}" />
                            </td>
                            <td width="32">
                                <img class="rounded" src="/{{$product->cover}}" width="32" height="32" role="img">
                            </td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->category->name}}</td>
                            <td>{{$product->price}}</td>
                            <td class="text-center">
                                @if ($product->status)
                                <span class="badge badge-success"><i class="fa fa-check"></i></span>
                                @else
                                <span class="badge badge-danger"><i class="fa fa-times"></i></span>
                                @endif
                            </td>
                            <td class="text-right">
                                @if (!auth()->user()->hasRole('cashier'))
                                <div class="dropdown">
                                    <button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{{route('product.edit',$product->id)}}">Edit</a>
                                        <a class="dropdown-item" href="{{route('product.destroy',$product->id)}}"
                                            data-toggle="confirm" data-message="Are you sure?">Hapus</a>
                                    </div>
                                </div>
                                @endif
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td class="table-empty" colspan="6">
                                <div class="table-empty-msg">
                                    <i class="fa fa-warning table-empty-icon"></i> No
                                    records
                                    found
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop