routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', ['as' => 'home', 'uses' => 'DashboardController@index']);
Route::get('home', ['as' => 'home', 'uses' => 'DashboardController@index']);

Route::group(['prefix' => 'categories', 'as' => 'category.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'CategoryController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'CategoryController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'CategoryController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'CategoryController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CategoryController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'CategoryController@update']);
});

Route::group(['prefix' => 'tables', 'as' => 'table.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'TableController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'TableController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'TableController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'TableController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'TableController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'TableController@update']);
});

Route::group(['prefix' => 'pos', 'as' => 'pos.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'PosController@index']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'PosController@edit']);
    Route::post('/', ['as' => 'add', 'uses' => 'PosController@add']);
    Route::get('orderList', 'PosController@orderList');
    Route::get('orderList/{id}', 'PosController@orderListEdit');
    Route::get('total', 'PosController@total');
    Route::get('total/{id}', 'PosController@totalEdit');
    Route::post('update', 'PosController@update');
    Route::put('process', ['as' => 'process', 'uses' => 'PosController@process']);
    Route::get('delete/{id}', ['as' => 'delete', 'uses' => 'PosController@destroy']);
    Route::post('payment', ['as' => 'payment', 'uses' => 'PosController@payment']);
    Route::get('payment/{id}', ['as' => 'paymentDetail', 'uses' => 'PosController@paymentDetail']);
});

Route::group(['prefix' => 'products', 'as' => 'product.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'ProductController@index']);
    Route::post('/', ['as' => 'store', 'uses' => 'ProductController@store']);
    Route::get('inventory', ['as' => 'inventory', 'uses' => 'ProductController@inventory']);
    Route::get('new', ['as' => 'create', 'uses' => 'ProductController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'ProductController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'ProductController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'ProductController@update']);

});

Route::group(['prefix' => 'sales', 'as' => 'sale.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'SaleController@index']);
    Route::get('opened', ['as' => 'opened', 'uses' => 'SaleController@opened']);
    Route::get('show/{id}', ['as' => 'show', 'uses' => 'SaleController@show']);
    Route::post('payment', ['as' => 'payment', 'uses' => 'SaleController@payment']);
    Route::get('payment/{id}', ['as' => 'paymentDetail', 'uses' => 'SaleController@paymentDetail']);
});

Route::group(['prefix' => 'users', 'as' => 'user.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'UserController@index']);
    Route::get('activity', ['as' => 'activity', 'uses' => 'UserController@activity']);
    Route::post('/', ['as' => 'store', 'uses' => 'UserController@store']);
    Route::get('new', ['as' => 'create', 'uses' => 'UserController@create']);
    Route::get('edit/{id}', ['as' => 'edit', 'uses' => 'UserController@edit']);
    Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'UserController@destroy']);
    Route::put('update/{id}', ['as' => 'update', 'uses' => 'UserController@update']);
});

Route::group(['prefix' => 'settings', 'as' => 'setting.'], function () {
    Route::get('/', ['as' => 'index', 'uses' => 'SettingController@index']);
    Route::put('/', ['as' => 'update', 'uses' => 'SettingController@update']);
});

Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@loginForm']);
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
});

app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Table;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class TableController extends Controller
{

    public function index()
    {
        $tables = Table::paginate(20);
        return view('table.index', compact('tables'));
    }

    public function create()
    {
        return view('table.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
        ]);

        if ($validator->fails()) {
            flash('Warning: Please check the form carefully for errors!')->error();
            return back()->withInput()->withErrors($validator);
        }

        $table = new Table([
            'name'   => $request->name,
            'active' => $request->active,
        ]);
        $table->save();

        $user = Auth::user();
        activity()->causedBy($user)->log($user->name . ' menambahkan kategori baru.');

        flash('Success: You have modified tables!')->success();
        return redirect()->route('table.index');
    }

    public function edit($id)
    {
        $table = Table::find($id);
        return view('table.edit', \compact('table'));
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
        ]);

        if ($validator->fails()) {
            flash('Warning: Please check the form carefully for errors!')->error();
            return back()->withInput()->withErrors($validator);
        }
        $table         = Table::find($id);
        $table->name   = $request->name;
        $table->active = $request->active;
        $table->update();

        flash('Success: You have modified tables!')->success();
        return back();
    }

    public function destroy($id)
    {
        $table = Table::find($id);
        $table->delete();

        flash('Success: You have deleted tables!')->success();
        return back();
    }
}

resources/views/table/create.blade.php
@extends('layouts.master')

@section('content')
<form action="{{route('table.store')}}" class="form-horizontal" method="POST">
    @csrf
    <div class="container">
        @include('flash::message')
        <div class="row">
            <div class="col-md-8">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">

                            <div class="form-group required">
                                <label class="col-form-label" for="inputName">Table Name</label>
                                <input class="form-control{{$errors->has('name')?' is-invalid':''}}" name="name" id="inputName"
                                    type="text" placeholder="e.g. Meja 01" value="{{old('name')}}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Visibility</strong>
                                </div>
                            </div>
                            <div class="form-group mt-2">
                                <div class="form-check">
                                    <input class="form-check-input" id="radio1" type="radio" value="1" name="active"
                                        {{old('active',1)?"checked":""}}>
                                    <label class="form-check-label" for="radio1">Visible</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" id="radio2" type="radio" value="0" name="active"
                                        {{old('active',1)?"":"checked"}}>
                                    <label class="form-check-label" for="radio2">Hidden</label>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
        <hr>
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="form-actions float-right">`
                    <button class="btn btn-secondary" type="button">Cancel</button>
                    <button class="btn btn-primary" type="submit">Save Category</button>
                </div>
            </div>
        </div>
    </div>
</form>
@stop

resources/views/table/edit.blade.php
@extends('layouts.master')

@section('content')
<form action="{{route('table.update',$table->id)}}" class="form-horizontal" method="POST">
    @csrf
    <input name="_method" type="hidden" value="PUT">
    <div class="container">
        @include('flash::message')
        <div class="row">
            <div class="col-md-8">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">

                            <div class="form-group required">
                                <label class="col-form-label" for="inputName">Table Name</label>
                                <input class="form-control{{$errors->has('name')?' is-invalid':''}}" name="name" id="inputName"
                                    type="text" placeholder="e.g. Meja 01" value="{{old('name',$table->name)}}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="animated fadeIn">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-12">
                                    <strong class="card-title mb-0">Visibility</strong>
                                </div>
                            </div>
                            <div class="form-group mt-2">
                                <div class="form-check">
                                    <input class="form-check-input" id="radio1" type="radio" value="1" name="active"
                                        {{old('active',1)?"checked":""}}>
                                    <label class="form-check-label" for="radio1">Visible</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" id="radio2" type="radio" value="0" name="active"
                                        {{old('active',1)?"":"checked"}}>
                                    <label class="form-check-label" for="radio2">Hidden</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <hr>
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="form-actions float-right">
                    <button class="btn btn-secondary" type="button">Cancel</button>
                    <button class="btn btn-primary" type="submit">Save Table</button>
                </div>
            </div>
        </div>
    </div>
</form>
@stop

resources/views/table/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="animated fadeIn">
        @include('flash::message')
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-5">
                        <h4 class="card-title mb-0">Manage Table</h4>
                    </div>
                    @if (!auth()->user()->hasRole('cashier'))
                    <div class="col-sm-7 d-none d-md-block">
                        <a class="btn btn-primary float-right" href="{{route('table.create')}}">
                            Add Table
                        </a>
                    </div>
                    @endif
                </div>
                <table class="table table-responsive-sm table-hover mt-4">
                    <thead>
                        <tr>
                            <th class="text-center">
                                <input type="checkbox" onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" />
                            </th>
                            <th>Table</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($tables as $item)
                        <tr>
                            <td class="text-center" width="10">
                                <input type="checkbox" name="selected[]" value="{{$item->id}}" />
                            </td>
                            <td>{{$item->name}}</td>
                            <td class="text-right">
                                @if (!auth()->user()->hasRole('cashier'))
                                <div class="dropdown">
                                    <button class="btn btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown">Actions</button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{{route('table.edit',$item->id)}}">Edit</a>
                                        <a class="dropdown-item" href="{{route('table.destroy',$item->id)}}"
                                            data-toggle="confirm" data-message="Are you sure?">Hapus</a>
                                    </div>
                                </div>
                                @endif
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td class="table-empty" colspan="4">
                                <div class="table-empty-msg">
                                    <i class="fa fa-warning table-empty-icon"></i> No
                                    records
                                    found
                                </div>
                            </td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop